### ISSUE TITLE
diffrence with adrifkat instagram

### ISSUE THREAD

**Issue by nemesisKO** [ammarbrohi/instagram-php#1]
whats the diffrence between this repository and adrifkat instagram?

**Comment by L7n111** [comment]
can't upload vids and imgs

**Comment by nemesisKO** [comment]
> can't upload vids and imgs

but this package cant be installed

**Comment by ammarbrohi** [comment]
@nemesisKO The adrifkat/instagram package was causing issues when executing it on web.
It used to display error like: can't run on web only console supported.

This packages works fine on web and uploads imgs/videos.

**Comment by ammarbrohi** [comment]
> > can't upload vids and imgs
> 
> but this package cant be installed

Let me know what error you're facing.

**Comment by nemesisKO** [comment]
> > > can't upload vids and imgs
> > 
> > 
> > but this package cant be installed
> 
> Let me know what error you're facing.

thank you very much man no problem detected
